/**
 * Bakes the Lvl badge's digit glyphs into src/card/digits.generated.ts.
 * Run: node scripts/bake-digits.mjs
 *
 * Only tex and tint are baked - the correction is per-pixel and independent of
 * where a glyph sits. shade stays at runtime: it also drives the ink gradient under
 * the texture, and baking it would put one number in two places that must agree.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SRC = path.join(ROOT, "assets", "digits");
const OUT = path.join(ROOT, "src", "card", "digits.generated.ts");

/** Re-bake when these move. */
const TREATMENT = { tex: 1, tint: 0.8 };

/**
 * How much of the field each channel keeps: v' = k.v + (1 - k). Red keeps the most,
 * so it darkens hardest, which is what tips the shading blue rather than grey.
 */
const keep = ({ tex, tint }) => [
  tex,
  tex * (1 - 0.3 * tint),
  tex * (1 - 0.75 * tint),
];

async function bakeTexture(file) {
  const grey = sharp(file).greyscale();
  const { data, info } = await grey.raw().toBuffer({ resolveWithObject: true });
  const k = keep(TREATMENT);
  const out = Buffer.alloc(info.width * info.height * 3);
  for (let i = 0; i < info.width * info.height; i++) {
    const v = data[i];
    for (let c = 0; c < 3; c++) {
      out[i * 3 + c] = Math.max(
        0,
        Math.min(255, Math.round(k[c] * v + (1 - k[c]) * 255)),
      );
    }
  }
  // Lossless here: the correction is a function of one grey value, so the result
  // only ever holds 256 distinct colours. A third the bytes of truecolour.
  return sharp(out, {
    raw: { width: info.width, height: info.height, channels: 3 },
  })
    .png({ compressionLevel: 9, palette: true, colours: 256, dither: 0 })
    .toBuffer();
}

const glyphs = {};
for (const ch of "0123456789") {
  const svg = fs.readFileSync(path.join(SRC, `${ch}.svg`), "utf8");
  const box = /viewBox="0 0 (\d+) (\d+)"/.exec(svg);
  const outline = /\sd="([^"]+)"/.exec(svg);
  if (!box || !outline)
    throw new Error(`cannot read outline or viewBox from ${ch}.svg`);
  const png = await bakeTexture(path.join(SRC, "texture", `${ch}.png`));
  glyphs[ch] = {
    width: Number(box[1]),
    height: Number(box[2]),
    outline: outline[1],
    texture: `data:image/png;base64,${png.toString("base64")}`,
  };
}

const body = Object.entries(glyphs)
  .map(
    ([ch, g]) => `  "${ch}": {
    width: ${g.width},
    height: ${g.height},
    outline:
      "${g.outline}",
    texture:
      "${g.texture}",
  },`,
  )
  .join("\n");

fs.writeFileSync(
  OUT,
  `// Generated by scripts/bake-digits.mjs - do not edit.
// Baked with tex ${TREATMENT.tex}, tint ${TREATMENT.tint}; re-run the script to change them.
import type { DigitGlyph } from "./lvl-badge";

export const DIGIT_GLYPHS: Record<string, DigitGlyph> = {
${body}
};
`,
);

const kb = (fs.statSync(OUT).size / 1024).toFixed(0);
console.log(
  `wrote ${path.relative(ROOT, OUT)} (${kb} KB, ${Object.keys(glyphs).length} glyphs)`,
);
